name: First Workflow

on:
  push: 
   branches:
     - main

jobs:
  example-job:
    runs-on: ubuntu-24.04

    steps:
      - name: print a welcome message
        run: echo "welcome to the family son!"

      - name: Checking out
        uses: actions/checkout@v6.0.2
